app = 'turbograph-bench'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[build.settings]
  context = "../../"

[mounts]
  source = "bench_data"
  destination = "/data"

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 4
