app = 'turbograph-bench'
primary_region = 'iad'

[build]
  dockerfile = "turbograph/bench/Dockerfile"

[build.settings]
  context = "../../"

[mounts]
  source = "bench_data"
  destination = "/data"

[[vm]]
  memory = '64gb'
  cpu_kind = 'performance'
  cpus = 8
